### ISSUE TITLE
crypto

### ISSUE THREAD

**Issue by claudiowwe** [ccuetoh/libreapi#2]
hola amigos, buena colección de apis, muchas gracias por lo que hacen, una pregunta, ¿como puedo buscar otras cryptos que no estan enlistadas?

**Comment by ccuetoh** [comment]
Hola! Me alegra que la API te haya resultado útil y gracias. 

La lista de criptomonedas que usa LibreAPI es extrída de CoinMarketCap desde este [link](https://coinmarketcap.com/all/views/all), y se limita a las 200 monedas con más valor en circulación (Market Cap). La busqueda por lo tanto se limita a esa lista de criptomonedas. Sin embargo revisando la situación creo que veo una forma de poder expandir la cantidad de criptomonedas. Mañana subiré un PR con los cambios.

**Comment by claudiowwe** [comment]
perfecto! buenísimo, estaré atento, gracias

**Comment by ccuetoh** [comment]
Lamentablemente hoy no pude y me voy de vacaciones por una semana. Cuando regrese lo reviso

**Comment by claudiowwe** [comment]
No te preocupes, estaré atento de todas maneras! Saludos

**Comment by ccuetoh** [comment]
Agregado en el commit 1e10642864c43e32c748d256a4a208f214925f9c

**Comment by claudiowwe** [comment]
hola buenas tardes, creo que no funciona el de crypto, no me genera ninguna respuesta, la respuesta solo carga y carga y no entrega nada :c

**Comment by ccuetoh** [comment]
Al parecer la API de CoinMarketCap estaba teniendo problemas de rendimiento ayer (de la cual LibreAPI depende) y por lo tanto estaba afectando el rendimiento del endpoint. Hoy parece estar normal, pero me avisas si tienes más inconvenientes
