### ISSUE TITLE
Server is Down

### ISSUE THREAD

**Issue by javier-benavide** [ccuetoh/libreapi#3]
Hi guys! Hope everything is OK. 

There is a problem with the Host, I used the API on friday 14 and everything was OK but today (Monday 17) all my request have the problem

<img width="1430" alt="Screen Shot 2022-10-17 at 10 07 18" src="https://user-images.githubusercontent.com/82097948/196185464-1987752b-ddac-4a68-ba82-762ce88447ea.png">

**Comment by ccuetoh** [comment]
Hi Javier, thanks for letting me know. The hosting provider is experiencing some issues and the API is currently down. I've already got in touch with them early morning, and they said they are working on resolving the issue.

I'll keep you posted, and sorry for the inconvenience!

**Comment by javier-benavide** [comment]
No problem, thank to you for this API!

Hope you have a nice week

**Comment by ccuetoh** [comment]
The problem appears to be resolved and the API is back online. If you have any further issues please don't doubt to let me know!
